### ISSUE TITLE
Roth app not Working on Homey

### ISSUE THREAD

**Issue by Flelar** [jonkristian/no.jonkristian.roth#1]
I Can not Connect Roth termostat getting this message : Cannot read property 'name' of undefined. What is the problem?

**Comment by khovik** [comment]
I get the same error message.

**Comment by jonkristian** [comment]
Sorry for the late reply.
I've recently ditched the homey so if anybody wants to adopt the app, let me know and I'll transfer.

**Comment by khovik** [comment]
I'll be happy to take over. Was able to get the app working by updating SDK version used.

**Comment by khovik** [comment]
Pull request to fix the issue, https://github.com/jonkristian/no.jonkristian.roth/pull/2

**Comment by arnljot** [comment]
@jonkristian and @khovik, have the application been transferred?
I'm a very satisfied user of this application, and would hate to see it wither and die.

**Comment by Flelar** [comment]
I don’t understand anything of this, i am just interestet in a Homey app Roth Touchline V1.0.3 upgrade

**Comment by arnljot** [comment]
@jonkristian The PR by @khovik was merged, but it's not yet published on the homey app store.

**Comment by arnljot** [comment]
> I don’t understand anything of this, i am just interestet in a Homey app Roth Touchline V1.0.3 upgrade

The problem you have has been fixed by khovik. But it's not been published yet by the original app author.

**Comment by jonkristian** [comment]
I am sorry this has not been taken care of sooner.
We're in the process of transferring the app, so it shouldn't be long now.

**Comment by henninfi** [comment]
I'm still struggling with the "Cannot read property 'name' of undefined". I'm connecting to the correct IP address and i've tried with khovik's new version. Still no luck. The descreption of the app says you need to set the controllers to slave <-> master. How do i check if this is done correctly? 

I've created an error-report through homey, report nr. 4a0725ae-a105-4821-b39e-83b184d97e66

**Comment by jonkristian** [comment]
> I'm still struggling with the "Cannot read property 'name' of undefined". I'm connecting to the correct IP address and i've tried with khovik's new version. Still no luck. The descreption of the app says you need to set the controllers to slave <-> master. How do i check if this is done correctly?
> 
> I've created an error-report through homey, report nr. 4a0725ae-a105-4821-b39e-83b184d97e66

Do you have any special names for your thermostats, can you check in the roth app to see if something stands out? The roth app/api is not well written, maybe even a name is missing? Do you have multiple controllers? If so, one controller needs to be slave, you should be able to figure this one out reading the roth manual. If you have one controller, you should be fine.

**Comment by henninfi** [comment]
> > I'm still struggling with the "Cannot read property 'name' of undefined". I'm connecting to the correct IP address and i've tried with khovik's new version. Still no luck. The descreption of the app says you need to set the controllers to slave <-> master. How do i check if this is done correctly?
> > I've created an error-report through homey, report nr. 4a0725ae-a105-4821-b39e-83b184d97e66
> 
> Do you have any special names for your thermostats, can you check in the roth app to see if something stands out? The roth app/api is not well written, maybe even a name is missing? Do you have multiple controllers? If so, one controller needs to be slave, you should be able to figure this one out reading the roth manual. If you have one controller, you should be fine.

Thanks alot for the quick reply! 

By controller i assume your refering to the thermostats!? If yes, i have 3. They are called, "Stue, Kjoekken and Vaskerom. 

I'll looking into making one of the controllers a slave.

**Comment by jonkristian** [comment]
@henninfi no, by controller i mean the main unit. I assume you've got only one so you're fine.

**Comment by khovik** [comment]
I found a bug in my PR. I'm currently back where I have my Roth installation, and doing testing on latest changes, before I'll submit the updates to Homey. I'm not sure how long they'll take to approve it.

@henninfi , the update should resolve your issue.

**Comment by khovik** [comment]
I dug around some more, and discovered a couple of issues. 
- Updating settings (ip address of Roth controller) was not picked up the app, resulting in the "undefined name" issue a many have been seeing.
- Updated the app to use SDK version 3.

I've submitted the changes for publishing, and those too eager to wait, can install it from here, https://homey.app/no-no/app/no.jonkristian.touchline/Roth-Touchline/test/ 

The app will get version 2.0.0, as updating to SDK version 3 is a potentially breaking change.  

God Jul!

**Comment by khovik** [comment]
Versjon 2.0.0 av app'n er publisert, og tilgjengelig for alle. https://homey.app/no-no/app/no.jonkristian.touchline/Roth-Touchline/

**Comment by henninfi** [comment]
Ny versjon fikset problemet 🙌🙌
